import React, { useEffect, useRef, useState, useCallback } from "react";
import { Html5Qrcode } from "html5-qrcode";
import { getCategoryMeta } from "../data/inventoryData";
import logoImg from "../assets/logo.jpg";
import "./QRScanner.css";

/* ─── Parse the text payload encoded in the QR ─── */
function parseQRPayload(raw, items = []) {
  const result = {};
  const rawStr = (raw || "").trim();

  // Compact sticker payload: ICT:AssetTag:ID
  if (rawStr.startsWith("ICT:")) {
    const parts = rawStr.split(":");
    const tag = parts[1] || "";
    const id  = parts[2] || parts[1] || "";

    const matched = items.find(
      (i) => (tag && i.assetTag?.toString() === tag) || (id && i.id?.toString() === id)
    );

    if (matched) {
      return {
        isICT: true,
        category: matched.category,
        device: matched.deviceType || matched.name,
        campus: matched.campus,
        department: matched.department,
        assigned_to: matched.assignedUser,
        status: matched.status,
        year: matched.yearPurchased,
        processor: matched.processor,
        ram: matched.ram,
        os: matched.os,
        storage: matched.storage,
        brand: matched.brand,
        model: matched.model,
        asset_tag: matched.assetTag || tag,
        id: matched.id,
        matchedItem: matched,
      };
    }

    return {
      isICT: true,
      asset_tag: tag,
      id: id,
    };
  }

  // URL deep link format: .../?assetTag=39250
  if (rawStr.includes("assetTag=") || rawStr.includes("id=")) {
    try {
      const url = new URL(rawStr);
      const tag = url.searchParams.get("assetTag") || "";
      const id  = url.searchParams.get("id") || "";
      const matched = items.find(
        (i) => (tag && i.assetTag?.toString() === tag) || (id && i.id?.toString() === id)
      );

      if (matched) {
        return {
          isICT: true,
          category: matched.category,
          device: matched.deviceType || matched.name,
          campus: matched.campus,
          department: matched.department,
          assigned_to: matched.assignedUser,
          status: matched.status,
          year: matched.yearPurchased,
          processor: matched.processor,
          ram: matched.ram,
          os: matched.os,
          storage: matched.storage,
          brand: matched.brand,
          model: matched.model,
          asset_tag: matched.assetTag || tag,
          id: matched.id,
          matchedItem: matched,
        };
      }
    } catch (_) {}
  }

  // Legacy multiline text payload
  const isICTText = rawStr.includes("ICT Hardware Inventory") || rawStr.includes("ICT HARDWARE ASSET");
  const lines = rawStr.split("\n").map((l) => l.trim()).filter(Boolean);
  for (const line of lines) {
    const colonIdx = line.indexOf(":");
    if (colonIdx === -1) continue;
    const key = line.slice(0, colonIdx).trim().toLowerCase().replace(/\s+/g, "_");
    const val = line.slice(colonIdx + 1).trim();
    if (val && val !== "—") result[key] = val;
  }
  result.isICT = isICTText;
  return result;
}

/* ─── Status colour helper ─── */
function statusColor(s) {
  if (s === "Functional")       return "#22c55e";
  if (s === "Defective")        return "#ef4444";
  if (s === "For Replacement")  return "#f97316";
  return "#f59e0b";
}

/* ─── Result Card shown after successful scan ─── */
function ScanResultCard({ parsed, rawText, onFindInInventory, onScanAgain }) {
  const isICT = parsed?.isICT || rawText.includes("ICT Hardware Inventory") || rawText.includes("ICT HARDWARE ASSET");
  const meta  = isICT ? getCategoryMeta(parsed.category) : null;

  if (!isICT) {
    return (
      <div className="scan-result non-ict">
        <div className="scan-result-icon">⚠️</div>
        <h3 className="scan-result-title">Not an ICT Inventory QR</h3>
        <p className="scan-result-sub">This QR code was not generated by the ICT Hardware Inventory system.</p>
        <div className="scan-raw-box"><pre>{rawText}</pre></div>
        <button className="scan-btn-again" onClick={onScanAgain}>📷 Scan Again</button>
      </div>
    );
  }

  return (
    <div className="scan-result ict-result">
      {/* Header */}
      <div className="sr-header">
        <img src={logoImg} alt="ICT" className="sr-logo" />
        <div className="sr-header-text">
          <span className="sr-sys">ICT Hardware Inventory</span>
          {meta && (
            <span className="sr-cat-badge" style={{ background: meta.color + "22", color: meta.color, borderColor: meta.color + "55" }}>
              {meta.icon} {parsed.category}
            </span>
          )}
        </div>
        <div className="sr-scan-ok">✅ Verified</div>
      </div>

      {/* Main caption – Department */}
      <div className="sr-dept-block">
        <span className="sr-dept-label">Department / Office</span>
        <span className="sr-dept-value">{parsed.department || parsed.campus || "—"}</span>
        {parsed.asset_tag && <span className="sr-asset-tag">#{parsed.asset_tag}</span>}
      </div>

      {/* Device name */}
      <div className="sr-device-row">
        <span className="sr-device-icon">{meta?.icon || "📦"}</span>
        <span className="sr-device-name">{parsed.device || "—"}</span>
        {parsed.status && (
          <span className="sr-status-pill" style={{ background: statusColor(parsed.status) + "22", color: statusColor(parsed.status), borderColor: statusColor(parsed.status) + "55" }}>
            {parsed.status}
          </span>
        )}
      </div>

      {/* Info grid */}
      <div className="sr-grid">
        {[
          ["Campus",      parsed.campus],
          ["Assigned To", parsed.assigned_to],
          ["Year",        parsed.year],
          ["Processor",   parsed.processor],
          ["RAM",         parsed.ram],
          ["OS",          parsed.os],
          ["Storage",     parsed.storage],
          ["Brand",       parsed.brand],
          ["Model",       parsed.model],
        ].filter(([, v]) => v).map(([label, val]) => (
          <div key={label} className="sr-grid-item">
            <span className="sr-gl">{label}</span>
            <span className="sr-gv">{val}</span>
          </div>
        ))}
      </div>

      {/* Actions */}
      <div className="sr-actions">
        {onFindInInventory && (
          <button className="scan-btn-find" onClick={() => onFindInInventory(parsed.matchedItem || parsed)}>
            🔍 Find in Inventory
          </button>
        )}
        <button className="scan-btn-again" onClick={onScanAgain}>📷 Scan Again</button>
      </div>
    </div>
  );
}

/* ─── Main QR Scanner Modal ─── */
export default function QRScanner({ items = [], onClose, onFindInInventory }) {
  const scannerRef   = useRef(null);
  const html5QrRef   = useRef(null);
  const fileInputRef = useRef(null);

  const [mode,       setMode]       = useState("camera"); // "camera" | "file"
  const [scanning,   setScanning]   = useState(false);
  const [result,     setResult]     = useState(null);   // { raw, parsed }
  const [error,      setError]      = useState(null);
  const [cameraList, setCameraList] = useState([]);
  const [camIdx,     setCamIdx]     = useState(0);
  const [torchOn,    setTorchOn]    = useState(false);

  /* ── Start camera scan ── */
  const startCamera = useCallback(async (cameraId) => {
    if (!scannerRef.current) return;
    setError(null);
    setResult(null);

    try {
      if (html5QrRef.current) {
        try { await html5QrRef.current.stop(); } catch (_) {}
        html5QrRef.current = null;
      }

      const qr = new Html5Qrcode("qr-scanner-viewport");
      html5QrRef.current = qr;

      await qr.start(
        cameraId,
        {
          fps: 15,
          qrbox: (w, h) => {
            const min = Math.min(w, h);
            const sz  = Math.round(min * 0.7);
            return { width: sz, height: sz };
          },
          aspectRatio: 1.0,
        },
        (decodedText) => {
          const parsed = parseQRPayload(decodedText, items);
          setResult({ raw: decodedText, parsed });
          setScanning(false);
          // stop after first successful scan
          try { qr.stop(); } catch (_) {}
        },
        (_err) => { /* frame decode errors — normal, ignore */ }
      );
      setScanning(true);
    } catch (e) {
      setError("Camera access denied or not available. Try uploading an image instead.");
      setScanning(false);
    }
  }, [items]);

  /* ── Enumerate cameras on mount ── */
  useEffect(() => {
    Html5Qrcode.getCameras()
      .then((cams) => {
        if (cams.length === 0) {
          setError("No cameras found on this device.");
          return;
        }
        setCameraList(cams);
        // prefer back/environment camera on mobile
        const backIdx = cams.findIndex((c) =>
          /back|rear|environment/i.test(c.label)
        );
        const idx = backIdx >= 0 ? backIdx : 0;
        setCamIdx(idx);
        startCamera(cams[idx].id);
      })
      .catch(() => {
        setError("Could not access cameras. Check browser permissions.");
      });

    return () => {
      if (html5QrRef.current) {
        try { html5QrRef.current.stop(); } catch (_) {}
      }
    };
  }, [startCamera]);

  /* ── Switch camera ── */
  const switchCamera = async () => {
    if (cameraList.length < 2) return;
    const next = (camIdx + 1) % cameraList.length;
    setCamIdx(next);
    await startCamera(cameraList[next].id);
  };

  /* ── Toggle torch (if supported) ── */
  const toggleTorch = async () => {
    if (!html5QrRef.current) return;
    try {
      await html5QrRef.current.applyVideoConstraints({
        advanced: [{ torch: !torchOn }],
      });
      setTorchOn((t) => !t);
    } catch (_) {
      // torch not supported — silently ignore
    }
  };

  /* ── Upload image file ── */
  const handleFileUpload = async (e) => {
    const file = e.target.files?.[0];
    if (!file) return;
    setError(null);
    setResult(null);

    // Stop camera if running
    if (html5QrRef.current) {
      try { await html5QrRef.current.stop(); } catch (_) {}
    }

    try {
      const qr = new Html5Qrcode("qr-scanner-viewport");
      html5QrRef.current = qr;
      const decodedText = await qr.scanFile(file, true);
      const parsed = parseQRPayload(decodedText, items);
      setResult({ raw: decodedText, parsed });
    } catch (_) {
      setError("Could not read a QR code from the uploaded image. Try a clearer photo.");
    }
    e.target.value = "";
  };

  /* ── Scan Again ── */
  const handleScanAgain = () => {
    setResult(null);
    setError(null);
    if (cameraList.length > 0) {
      startCamera(cameraList[camIdx].id);
    }
  };

  return (
    <div className="qrs-backdrop" onClick={onClose}>
      <div className="qrs-modal" onClick={(e) => e.stopPropagation()}>

        {/* Header */}
        <div className="qrs-header">
          <div className="qrs-header-left">
            <img src={logoImg} alt="ICT" className="qrs-logo" />
            <div>
              <h2 className="qrs-title">QR Code Scanner</h2>
              <p className="qrs-sub">Scan any ICT Hardware Inventory QR code</p>
            </div>
          </div>
          <button className="qrs-close" onClick={onClose}>✕</button>
        </div>

        {/* Mode tabs */}
        <div className="qrs-mode-tabs">
          <button
            className={`qrs-tab ${mode === "camera" ? "active" : ""}`}
            onClick={() => { setMode("camera"); handleScanAgain(); }}
          >
            📷 Camera
          </button>
          <button
            className={`qrs-tab ${mode === "file" ? "active" : ""}`}
            onClick={() => {
              setMode("file");
              if (html5QrRef.current) try { html5QrRef.current.stop(); } catch (_) {}
              setScanning(false);
              fileInputRef.current?.click();
            }}
          >
            🖼️ Upload Image
          </button>
        </div>

        {/* Viewport area */}
        <div className="qrs-viewport-wrap">
          {!result && (
            <div className="qrs-viewport" id="qr-scanner-viewport" ref={scannerRef}>
              {/* html5-qrcode injects video/canvas here */}
            </div>
          )}

          {/* Scanning overlay UI */}
          {scanning && !result && (
            <div className="qrs-scanner-overlay" aria-live="polite">
              <div className="qrs-corner qrs-tl" />
              <div className="qrs-corner qrs-tr" />
              <div className="qrs-corner qrs-bl" />
              <div className="qrs-corner qrs-br" />
              <div className="qrs-scan-line" />
              <span className="qrs-scanning-label">Scanning…</span>
            </div>
          )}

          {/* Camera controls (only when scanning live camera) */}
          {scanning && mode === "camera" && (
            <div className="qrs-cam-controls">
              {cameraList.length > 1 && (
                <button className="qrs-ctrl-btn" onClick={switchCamera} title="Switch camera">
                  🔄
                </button>
              )}
              <button className="qrs-ctrl-btn" onClick={toggleTorch} title="Torch">
                {torchOn ? "🔆" : "🔦"}
              </button>
            </div>
          )}

          {/* Result card */}
          {result && (
            <ScanResultCard
              parsed={result.parsed}
              rawText={result.raw}
              onFindInInventory={onFindInInventory}
              onScanAgain={handleScanAgain}
            />
          )}
        </div>

        {/* Error */}
        {error && !result && (
          <div className="qrs-error">
            <span>⚠️</span> {error}
          </div>
        )}

        {/* Hidden file input */}
        <input
          ref={fileInputRef}
          type="file"
          accept="image/*"
          style={{ display: "none" }}
          onChange={handleFileUpload}
        />

        {/* Footer tip */}
        {!result && (
          <p className="qrs-tip">
            💡 Point the camera at any device QR code, or tap <strong>Upload Image</strong> to scan from a photo.
          </p>
        )}
      </div>
    </div>
  );
}
